Repository iver-wharf/iver-wharf.github.io, pull requests merged in 2021-03, with the labels that each got.

#2 Added swagger-self-hosted.md
  docs/_sidebar.md
  docs/reference/swagger-self-hosted.md
Labels: documentation

#5 Added logo and favicon
  docs/_coverpage.md
  docs/_static/favicon.ico
  docs/_static/logo.svg
  docs/index.html
Labels: documentation

#4 Added docs on JSON/YAML schema
  docs/_images/wharf-ci-yml-json-schema-preview.png
  docs/_sidebar.md
  docs/_static/wharf-ci-schema.json
  docs/index.html
  docs/usage-wharfyml/json-yaml-schema-for-wharf-ci-yml.md
Labels: documentation

#1 The .wharf-ci.yml file
  docs/_sidebar.md
  docs/usage-wharfyml/the-wharf-ci-yml-file.md
Labels: documentation

#7 Added "About Wharf" to the landing page
  docs/README.md
  docs/index.html
Labels: documentation

#3 Added development HowTo's
  docs/_images/debugging-in-goland/breakpoint.png
  docs/_images/debugging-in-goland/edit-conf1.png
  docs/_images/debugging-in-goland/edit-conf2.png
  docs/_images/debugging-in-goland/edit-conf3.png
  docs/_images/debugging-in-goland/edit-conf4.png
  docs/_images/debugging-in-goland/edit-conf5.png
  docs/_images/debugging-in-goland/edit-conf6.png
  docs/_images/debugging-in-goland/running-app.png
  docs/_images/icon-goland.svg
  docs/_sidebar.md
  docs/development/debugging-in-goland.md
  docs/development/postgres-and-column-named-default.md
  docs/index.html
Labels: documentation

#6 Added footer
  docs/_footer.md
  docs/_static/site.css
  docs/index.html
Labels: documentation

#8 Fixed "Documentation" link since #7
  docs/_coverpage.md
Labels: bug

#12 Added fontawesome external link to all target="_blank"
  docs/_static/fontawesome-5.15.2/LICENSE.txt
  docs/_static/fontawesome-5.15.2/css/all.min.css
  docs/_static/fontawesome-5.15.2/webfonts/fa-brands-400.eot
  docs/_static/fontawesome-5.15.2/webfonts/fa-brands-400.svg
  docs/_static/fontawesome-5.15.2/webfonts/fa-brands-400.ttf
  docs/_static/fontawesome-5.15.2/webfonts/fa-brands-400.woff
  docs/_static/fontawesome-5.15.2/webfonts/fa-brands-400.woff2
  docs/_static/fontawesome-5.15.2/webfonts/fa-regular-400.eot
  docs/_static/fontawesome-5.15.2/webfonts/fa-regular-400.svg
  docs/_static/fontawesome-5.15.2/webfonts/fa-regular-400.ttf
  docs/_static/fontawesome-5.15.2/webfonts/fa-regular-400.woff
  docs/_static/fontawesome-5.15.2/webfonts/fa-regular-400.woff2
  docs/_static/fontawesome-5.15.2/webfonts/fa-solid-900.eot
  docs/_static/fontawesome-5.15.2/webfonts/fa-solid-900.svg
  docs/_static/fontawesome-5.15.2/webfonts/fa-solid-900.ttf
  docs/_static/fontawesome-5.15.2/webfonts/fa-solid-900.woff
  docs/_static/fontawesome-5.15.2/webfonts/fa-solid-900.woff2
  docs/_static/site.css
  docs/index.html
Labels: enhancement

#13 Added links to go docs
  docs/_sidebar.md
Labels: documentation

#11 Dark theme
  docs/_static/logo.svg
  docs/_static/site.css
  docs/index.html
Labels: enhancement

#14 Removed externallink icon from coverpage
  docs/_static/site.css
Labels: bug
